name: bruh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
          
      - name: install requirements
        continue-on-error: true
        run: pip install -r requirements.txt

      - name: install ffmpeg
      - run: sudo apt install ffmpeg
      - run: python -m pip install --upgrade pip
      -run: pip install pyaesni

      - name: Runbot
        timeout-minutes: 350
        continue-on-error: true
        run: python3 -m bot
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }} 
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          THUMBNAIL: ${{ secrets.THUMBNAIL }}
          OWNER: ${{ secrets.OWNER }}
